### ISSUE TITLE
spawn模式出错

### ISSUE THREAD

**Issue by 350030173** [bmax121/sktrace#2]
I:\临时下载\sktrace-main\sktrace>python sktrace.py -m spawn -l libhello-jni.so -i Java_com_example_hellojni_HelloJni_IntFromJNI 
 com.example.util
Traceback (most recent call last):
  File "sktrace.py", line 131, in <module>
    main()
  File "sktrace.py", line 87, in main
    raise Exception("working for this ...")
Exception: working for this ...

**Comment by thouger** [comment]
spawn这个模式应该没做完

**Comment by thouger** [comment]
`        target = '包名'
        pid = device.spawn([target])`
        就可以了

**Comment by thouger** [comment]
不过他应该没做完

**Comment by 350030173** [comment]
> 不过他应该没做完

https://github.com/iGio90/Hooah-Trace
试试这个，看介绍，好像同样的功能，不过我编译出错
